import Head from 'next/head';
import React from 'react';
import Footer from '../components/Shared/footer';
import NavigationBar from '../components/Shared/navigation';

interface LayoutProps {
    title?: string;
}

const Layout: React.FC<LayoutProps> = ({ children, title = 'Skyhub inventory app' }) => {
    return (
        <div className="flex flex-col min-h-screen">
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <NavigationBar />
            <main className="flex-1 container mx-auto p-4">
                {children}
            </main>
            <Footer/>
        </div>
    );
};

export default Layout;
